
A = -P.L_pos*cur(1:k)/P.sigma_pos-P.L_neg*cur(1:k)/P.sigma_neg ...
+P.L_pos/P.n_pos*sum(il(P.bnd_pos_sep:P.nj-1,1:k)+il(P.bnd_pos_sep+1:P.nj,1:k))/2 ...
+P.L_neg/P.n_neg*sum(il(1:P.bnd_sep_neg-1,1:k)+il(2:P.bnd_sep_neg,1:k))/2;